level_2/config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  resources :messages, only: %i[index show create]

  get '/tags/:name/messages', to: 'messages#messages_by_tag', as: :tag_messages
end

level_2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

level_2/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :tag
  belongs_to :user

  validates :content, presence: true
end

level_2/app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :messages

  # VALID_TAGS = ['urgent', 'secret', 'rigolo']
  VALID_TAGS = %w[urgent secret rigolo].freeze

  validates :tag, presence: true, inclusion: { in: VALID_TAGS, message: 'This is not a valid tag' }
end

level_2/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, :first_name, :last_name, presence: true

  has_many :messages
end

level_2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def after_sign_in_path_for(_resource)
    messages_path
  end
end

level_2/app/controllers/messages_controller.rb
require_relative '../../../level_1/traduction'

class MessagesController < ApplicationController

  include Translation

  before_action :set_message, only: :show
  before_action :authenticate_user!

  def index
    @messages = Message.all
    @tags = Tag.all
  end

  def show
    @translation = Translation.encode(@message.content)
  end

  def create
    content = params[:content]
    tag_id = params[:tag_id]
    @message = Message.create(
      content:,
      tag_id:,
      user: current_user
    )
    if @message.save
      redirect_to message_path(@message)
    else
      render 'index', status: :unprocessable_entity
    end
  end

  def messages_by_tag
    @tag_name = params[:name]
    tag = Tag.find_by(tag: @tag_name)
    @messages = tag ? Message.where(tag:) : nil
    @emoji = ''
    @emoji = '🔑' if @tag_name == 'secret'
    @emoji = '🤣' if @tag_name == 'rigolo'
    @emoji = '⚠' if @tag_name == 'urgent'

  end

  private

  def set_message
    @message = Message.find(params[:id])
  end
end

level_2/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

level_2/app/helpers/application_helper.rb
module ApplicationHelper
end

level_2/app/helpers/messages_helper.rb
module MessagesHelper
end

level_2/app/helpers/pages_helper.rb
module PagesHelper
end

level_2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PiouApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="">
      <%= yield %>
    </main>
  </body>
</html>

level_2/app/views/messages/index.html.erb
<div class="flex flex-row">
  <div class="basis-1/12"></div>
  <div class="basis-10/12">
    <h1 class="text-3xl font-bold text-center my-4 py-4">🧙‍♂️ Piou App Messages 🐦</h1>
  </div>
  <div class="basis-1/12 p-4">
    <%= button_to 'log out', destroy_user_session_path, method: :delete %>
  </div>
</div>

<div class="flex flex-row">
  <div class="basis-1/6"></div>
  <div class="basis-4/6">
    <div class="flex justify-between text-md font-medium text-center border-b-2 border-slate-400 px-5 pt-5">
      <% @tags.each do |tag| %>
        <div class="mx-1 bg-slate-300 rounded-t-xl p-4 hover:bg-slate-400/50 shadow-md">
          <%= link_to "#{tag.tag} messages", tag_messages_path(tag.tag) %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="basis-1/6"></div>
</div>

<div class="flex flex-row p-4">
  <div class="basis-2/3 p-4">
    <% @messages.each do |message| %>
      <%= link_to message_path(message) do %>
        <div class="mx-4 my-2 bg-slate-300 p-5 flex flex-row shadow-md hover:shadow-lg rounded-lg">
          <div class="basis-3/4 p-2">
            <p> <%= message.user.first_name %> <%= message.user.last_name %> </p>
            <p> <%= message.content %> </p>
          </div>
          <div class="basis-1/4 p-2 flex justify-end items-center">
            <p>see translation</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="basis-1/3 p-4 me-2">
    <div class="w-full box-border">
      <h3 class="text-center text-xl p-2">Post a message</h3>
      <div data-controller="post-message">
        <form data-action="submit->post-message#addMessage">
          <input type="text" class="slate-input w-full mb-2" placeholder="your message" name="message">
          <p class="m2">What kind of message is it?</p>
          <div class="flex flex-row">
            <% @tags.each do |tag| %>
              <div
                class="basis-1/3 bg-slate-300 m-3 shadow-sm hover:shadow-md rounded-lg p-4 flex items-center justify-center"
                data-action="click->post-message#handleClick"
                data-tagid=<%= tag.id %>
                data-post-message-target="tagDiv"
              >
                <%= tag.tag %>
              </div>
            <% end %>
          </div>
          <div class="flex justify-end me-3 mt-3">
            <input type="submit" class="bg-cyan-500/40 p-3 rounded-lg shadow-md hover:shadow-cyan-600/50 shadow-cyan-500/50" value="send message!" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

level_2/app/views/messages/messages_by_tag.html.erb
<div class="p-4 m-3">
  <%= link_to "↩ return", messages_path %>
</div>
<% if @messages %>
  <h2 class="text-2xl text-center mb-4">All <%= @tag_name %> messages <%= @emoji %> </h2>
  <div class="flex flex-row">
    <div class="basis-1/12"></div>
    <div class="basis-10/12">
      <div class="grid grid-cols-3 gap-5">
        <% @messages.each do |message| %>
          <%= link_to message_path(message) do %>
            <div class="bg-slate-300 shadow-md hover:shadow-lg rounded p-4">
              <p> <%= message.user.first_name %> <%= message.user.last_name %> </p>
              <p> <%= message.content %> </p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="basis-1/12"></div>
  </div>
<% end %>
<% if !@messages %>
  <h2 class="text-2xl text-center mb-4">There are no <%= @tag_name %> messages 🙄</h2>
<% end %>

level_2/app/views/messages/show.html.erb
<div class="p-4 m-3">
  <%= link_to "↩ return", messages_path %>
</div>

<div class="flex flex-row">
  <div class="basis-1/4"></div>
  <div class="basis-1/2">
    <div class="bg-slate-300 shadow-md rounded-lg p-4">
      <h2 class="text-xl text-center"> <%= @message.tag.tag %> </h1>
      <div class="m-3 p-3">
        <p class="mb-3 text-lg">🧙‍♂️ <%= @message.content %> </p>
        <p class="text-lg">🐦 <%= @translation %> </p>
      </div>
      <div class="flex justify-end">
        <div class="text-lg me-5">
          <p>from <%= @message.user.first_name %> <%= @message.user.last_name %> </p>
        </div>
      </div>
    </div>
  </div>
  <div class="basis-1/4"></div>
</div>

level_2/app/views/pages/home.html.erb
<div>
  <h1 class="font-bold text-5xl text-center m-5 p-5">Welcome to the Piou App!</h1>

  <div class="flex flex-row">
    <div class="basis-1/3"></div>
    <div class="basis-1/3">
      <%= link_to new_user_session_path do %>
        <div class="bg-slate-300 p-5 m-3 shadow-md rounded-lg text-center">
          Sign in
        </div>
      <% end %>
      <%= link_to new_user_registration_path do %>
        <div class="bg-slate-300 p-5 m-3 shadow-md rounded-lg text-center">
          Sign up
        </div>
      <% end %>
      <%= link_to messages_path do %>
        <div class="bg-slate-300 p-5 m-3 shadow-md rounded-lg text-center">
          see messages
        </div>
      <% end %>
    </div>
    <div class="basis-1/3"></div>
  </div>
</div>